### ISSUE TITLE
Question on: ability to input IPASIR solvers as a subject to automatic tuners

### ISSUE THREAD

**Issue by mww-aws** [ipasir2/ipasir2#34]
I have a question (perhaps just on the README.md) file.

One of the bullet points is "ability to input IPASIR solvers as a subject to automatic tuners".  I do not see how this is a capability of the IPASIR interface per se, but more of a result due to the capabilities that are present in the interface.  Could you either elaborate on this bullet (what capabilities does it require/add of the interface) or remove it?

**Comment by Udopia** [comment]
The readme contains a list of functions that have been requested by users of the IPASIR standard. The statement does not refer to the existence of such a function in the solver, but to the fact that one would like to access it via a standardized function.
